# Generated by Django 4.1.3 on 2022-12-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100, null=True)),
                ('lastname', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=300, null=True)),
                ('phone', models.CharField(max_length=18, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('type', models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor'), ('Lab Owner', 'Lab Owner'), ('Test Center Head', 'Test Center Head')], max_length=300, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='institute',
            name='services',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Closed', 'Closed')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='type',
            field=models.CharField(choices=[('Medical Clinic', 'Medical Clinic'), ('Dentist Clinic', 'Dentist Clinic'), ('Hospital', 'Hospital'), ('Lab', 'Lab'), ('Test Center', 'Test Center')], max_length=500, null=True),
        ),
    ]
