# Generated by Django 4.1.3 on 2022-12-02 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_user_institute_services_institute_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='related_institute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institute'),
        ),
    ]
