# Generated by Django 4.1.3 on 2022-12-03 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_tag_institute_tags_user_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
